spring:
  main:
    web-application-type: servlet
  shell:
    noninteractive.enabled: false
server:
  port: 8062

#logging:
#  level:
#    com.excentric.client.LoggingInterceptor: DEBUG
#  file:
#    name: logs/rest-client.log
#  pattern:
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

music-album-label-maker:
  api.user-agent: "MusicAlbumLabelMaker/0.0.1 (nfc-sonos@excentric.com)"
  musicbrainz:
    api.url: https://musicbrainz.org/ws/2/
    release-year-covers-only: true
  cover-art-archive.url: https://coverartarchive.org/
  metadata-directory: ${user.home}/.malm/metadata
  pdf-directory: ${user.home}/.malm/pdfs
